name: iris
description: "A lightweight video player"
publish_to: 'none'
version: 1.3.1+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  file_picker: ^8.1.4
  flutter_breadcrumb: ^1.0.1
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^8.1.0
  flutter_zustand: ^0.0.5
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  path: ^1.9.0
  path_provider: ^2.1.5
  package_info_plus: ^8.1.1
  provider: ^6.1.2
  webdav_client: ^1.2.2
  window_manager: ^0.4.3
  url_launcher: ^6.3.1
  scrollable_positioned_list: ^0.3.8
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  window_size: ^0.1.0
  uuid: ^4.5.1
  flutter_markdown: ^0.7.5
  http: ^1.2.2
  collection: ^1.19.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  disks_desktop: ^1.0.1
  android_x_storage: ^1.0.2
  permission_handler: ^11.3.1
  desktop_drop: ^0.5.0
  app_links: ^6.3.3
  device_info_plus: ^11.2.1
  saf_util: ^0.6.2
  screen_brightness: ^0.2.2
  flutter_volume_controller: ^1.3.3
  # fvp: ^0.29.0
  fvp:
    git:
      url: https://github.com/wang-bin/fvp
      ref: master
  video_player: ^2.9.2
  wakelock_plus: ^1.2.10
  popover: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.4
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/